services:
  reperr:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
      - ./src/appsettings.json:/app/src/appsettings.json
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    extra_hosts:
    - "host.docker.internal:host-gateway"